//! Reference tests that verify Rust implementations match Python outputs.
//!
//! These tests read expected values from xlsx fixtures generated by the Python
//! rolling-ta library and verify our Rust implementations produce identical results.
//!
//! Column positions from tests/fixtures/data_sheets.py (0-indexed, NO headers in files):
//! - btc-sma.xlsx: timestamp(0), close(1), sma(2)
//! - btc-ema.xlsx: timestamp(0), close(1), ema(2)
//! - btc-wma.xlsx: timestamp(0), close(1), weights(2), weighted_sum(3), wma(4)
//! - btc-hma.xlsx: timestamp(0), close(1), weights(2), wma_sqrt_sum(3), wma_sqrt(4),
//!                 wma_half_sum(5), wma_half(6), wma_full_sum(7), wma_full(8),
//!                 hma_raw(9), hma_raw_sum(10), hma(11)
//! - btc-rsi.xlsx: timestamp(0), close(1), gain(2), loss(3), gain_14(4), loss_14(5), rsi(6), ...
//! - btc-bb.xlsx: timestamp(0), close(1), sma(2), upper(3), lower(4)
//! - btc-atr.xlsx: timestamp(0), high(1), low(2), close(3), tr(4), atr(5)
//! - btc-obv.xlsx: timestamp(0), close(1), volume(2), up(3), down(4), obv(5)
//! - btc-adx.xlsx: timestamp(0), high(1), low(2), close(3), tr(4), atr(5),
//!                 h-h_p(6), l_p-l(7), +dx(8), -dx(9), +dx_14(10), -dx_14(11),
//!                 +dmi(12), -dmi(13), dx(14), adx(15)
//! - btc-linear_regression.xlsx: timestamp(0), high(1), low(2), close(3), typical(4),
//!                               row(5), intercept(6), slope(7), lr2(8), forecast(9)
//! - btc-vwap.xlsx: timestamp(0), timestamp_mod(1), high(2), low(3), close(4),
//!                  typical(5), volume(6), raw_accum(7), vol_accum(8), vwap(9)
//! - btc-roc.xlsx: timestamp(0), open(1), high(2), low(3), close(4), volume(5), roc_14(6)

use calamine::{open_workbook, Data, Reader, Xlsx};
use rolling_ta::prelude::*;
use rolling_ta::trend::{ADX, ADXConfig, EMA, EMAConfig, HMA, HMAConfig, SMA, SMAConfig, WMA, WMAConfig,
                        LinearRegression, LinearRegressionR2, LinearRegressionForecast, LinearRegressionConfig};
use rolling_ta::momentum::{ROC, ROCConfig, RSI, RSIConfig};
use rolling_ta::volatility::{ATR, ATRConfig, BB, BBConfig, TR};
use rolling_ta::volume::{OBV, VWAP, VWAPConfig};

const EPSILON: f64 = 1e-4; // Tolerance for floating point comparison

/// Helper to read xlsx file columns by position (NO headers in files).
fn read_xlsx_by_position(path: &str, col_indices: &[usize]) -> Vec<Vec<f64>> {
    let mut workbook: Xlsx<_> =
        open_workbook(path).unwrap_or_else(|_| panic!("Failed to open {}", path));

    let sheet_name = workbook.sheet_names()[0].clone();
    let range = workbook
        .worksheet_range(&sheet_name)
        .expect("Failed to read sheet");

    let mut result: Vec<Vec<f64>> = col_indices.iter().map(|_| Vec::new()).collect();

    // Read all rows (no header to skip)
    for row in range.rows() {
        for (result_idx, &col_idx) in col_indices.iter().enumerate() {
            let value = match row.get(col_idx) {
                Some(Data::Float(f)) => *f,
                Some(Data::Int(i)) => *i as f64,
                Some(Data::Empty) => f64::NAN,
                _ => f64::NAN,
            };
            result[result_idx].push(value);
        }
    }

    result
}

/// Build OhlcvSeries from closes only
fn build_ohlcv_from_closes(closes: &[f64]) -> OhlcvSeries {
    OhlcvSeries::from_closes(closes)
}

/// Build OhlcvSeries with high, low, close
fn build_ohlcv_hlc(highs: &[f64], lows: &[f64], closes: &[f64]) -> OhlcvSeries {
    let mut data = OhlcvSeries::with_capacity(closes.len());
    for i in 0..closes.len() {
        data.timestamps.push(i as i64);
        data.opens.push(closes[i]);
        data.highs.push(highs[i]);
        data.lows.push(lows[i]);
        data.closes.push(closes[i]);
        data.volumes.push(0.0);
    }
    data
}

/// Build OhlcvSeries with close and volume
fn build_ohlcv_cv(closes: &[f64], volumes: &[f64]) -> OhlcvSeries {
    let mut data = OhlcvSeries::with_capacity(closes.len());
    for i in 0..closes.len() {
        data.timestamps.push(i as i64);
        data.opens.push(closes[i]);
        data.highs.push(closes[i]);
        data.lows.push(closes[i]);
        data.closes.push(closes[i]);
        data.volumes.push(volumes[i]);
    }
    data
}

/// Build OhlcvSeries with timestamp, high, low, close, volume (for VWAP)
fn build_ohlcv_thlcv(
    timestamps: &[f64],
    highs: &[f64],
    lows: &[f64],
    closes: &[f64],
    volumes: &[f64],
) -> OhlcvSeries {
    let mut data = OhlcvSeries::with_capacity(closes.len());
    for i in 0..closes.len() {
        data.timestamps.push(timestamps[i] as i64);
        data.opens.push(closes[i]); // Use close as open (not needed for VWAP)
        data.highs.push(highs[i]);
        data.lows.push(lows[i]);
        data.closes.push(closes[i]);
        data.volumes.push(volumes[i]);
    }
    data
}

/// Compare two f64 slices, counting matches within epsilon
fn compare_values(name: &str, rust_values: &[f64], true_values: &[f64], epsilon: f64) -> usize {
    let mut comparisons = 0;
    for (i, (rust_val, true_val)) in rust_values.iter().zip(true_values.iter()).enumerate() {
        if !rust_val.is_nan() && !true_val.is_nan() {
            let diff = (rust_val - true_val).abs();
            assert!(
                diff < epsilon,
                "{} mismatch at index {}: Rust={:.6}, Expected={:.6}, diff={:.6}",
                name,
                i,
                rust_val,
                true_val,
                diff
            );
            comparisons += 1;
        }
    }
    comparisons
}

// ============================================================
// SMA Reference Tests
// ============================================================

#[test]
fn sma_matches_reference() {
    // btc-sma.xlsx: timestamp(0), close(1), sma(2)
    let cols = read_xlsx_by_position("resources/data/btc-sma.xlsx", &[1, 2]);
    let closes = &cols[0];
    let expected = &cols[1];

    let data = build_ohlcv_from_closes(closes);

    let mut sma = SMA::new(SMAConfig::new(14));
    sma.calc(&data).unwrap();

    let comparisons = compare_values("SMA", sma.history(), expected, EPSILON);
    println!("SMA: {} values compared successfully", comparisons);
    assert!(
        comparisons > 100,
        "Should have compared many values, got {}",
        comparisons
    );
}

#[test]
fn sma_streaming_matches_batch() {
    let cols = read_xlsx_by_position("resources/data/btc-sma.xlsx", &[1]);
    let closes = &cols[0];

    let data = build_ohlcv_from_closes(closes);

    // Batch calculation
    let mut batch_sma = SMA::new(SMAConfig::new(14));
    batch_sma.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_sma = SMA::new(SMAConfig::new(14));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_sma.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_sma.len(), stream_sma.len());

    for i in 0..batch_sma.len() {
        let batch_val = batch_sma.get(i as isize).unwrap();
        let stream_val = stream_sma.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch SMA ({}) and stream SMA ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch SMA ({}) != stream SMA ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

// ============================================================
// EMA Reference Tests
// ============================================================

#[test]
fn ema_matches_reference() {
    // btc-ema.xlsx: timestamp(0), close(1), ema(2)
    let cols = read_xlsx_by_position("resources/data/btc-ema.xlsx", &[1, 2]);
    let closes = &cols[0];
    let expected = &cols[1];

    let data = build_ohlcv_from_closes(closes);

    let mut ema = EMA::new(EMAConfig::new(14));
    ema.calc(&data).unwrap();

    let comparisons = compare_values("EMA", ema.history(), expected, EPSILON);
    println!("EMA: {} values compared successfully", comparisons);
    assert!(
        comparisons > 100,
        "Should have compared many values, got {}",
        comparisons
    );
}

#[test]
fn ema_streaming_matches_batch() {
    let cols = read_xlsx_by_position("resources/data/btc-ema.xlsx", &[1]);
    let closes = &cols[0];

    let data = build_ohlcv_from_closes(closes);

    // Batch calculation
    let mut batch_ema = EMA::new(EMAConfig::new(14));
    batch_ema.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_ema = EMA::new(EMAConfig::new(14));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_ema.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_ema.len(), stream_ema.len());

    for i in 0..batch_ema.len() {
        let batch_val = batch_ema.get(i as isize).unwrap();
        let stream_val = stream_ema.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch EMA ({}) and stream EMA ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch EMA ({}) != stream EMA ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

// ============================================================
// WMA Reference Tests
// ============================================================

#[test]
fn wma_matches_reference() {
    // btc-wma.xlsx: timestamp(0), close(1), weights(2), weighted_sum(3), wma(4)
    let cols = read_xlsx_by_position("resources/data/btc-wma.xlsx", &[1, 4]);
    let closes = &cols[0];
    let expected = &cols[1];

    let data = build_ohlcv_from_closes(closes);

    let mut wma = WMA::new(WMAConfig::new(14));
    wma.calc(&data).unwrap();

    let comparisons = compare_values("WMA", wma.history(), expected, EPSILON);
    println!("WMA: {} values compared successfully", comparisons);
    assert!(
        comparisons > 100,
        "Should have compared many values, got {}",
        comparisons
    );
}

#[test]
fn wma_streaming_matches_batch() {
    let cols = read_xlsx_by_position("resources/data/btc-wma.xlsx", &[1]);
    let closes = &cols[0];

    let data = build_ohlcv_from_closes(closes);

    // Batch calculation
    let mut batch_wma = WMA::new(WMAConfig::new(14));
    batch_wma.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_wma = WMA::new(WMAConfig::new(14));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_wma.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_wma.len(), stream_wma.len());

    for i in 0..batch_wma.len() {
        let batch_val = batch_wma.get(i as isize).unwrap();
        let stream_val = stream_wma.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch WMA ({}) and stream WMA ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch WMA ({}) != stream WMA ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

// ============================================================
// HMA Reference Tests
// ============================================================

#[test]
fn hma_matches_reference() {
    // btc-hma.xlsx: ..., hma(11)
    let cols = read_xlsx_by_position("resources/data/btc-hma.xlsx", &[1, 11]);
    let closes = &cols[0];
    let expected = &cols[1];

    let data = build_ohlcv_from_closes(closes);

    let mut hma = HMA::new(HMAConfig::new(14));
    hma.calc(&data).unwrap();

    let comparisons = compare_values("HMA", hma.history(), expected, EPSILON);
    println!("HMA: {} values compared successfully", comparisons);
    assert!(
        comparisons > 100,
        "Should have compared many values, got {}",
        comparisons
    );
}

#[test]
fn hma_streaming_matches_batch() {
    let cols = read_xlsx_by_position("resources/data/btc-hma.xlsx", &[1]);
    let closes = &cols[0];

    let data = build_ohlcv_from_closes(closes);

    // Batch calculation
    let mut batch_hma = HMA::new(HMAConfig::new(14));
    batch_hma.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_hma = HMA::new(HMAConfig::new(14));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_hma.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_hma.len(), stream_hma.len());

    for i in 0..batch_hma.len() {
        let batch_val = batch_hma.get(i as isize).unwrap();
        let stream_val = stream_hma.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch HMA ({}) and stream HMA ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch HMA ({}) != stream HMA ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

// ============================================================
// RSI Reference Tests
// ============================================================

#[test]
fn rsi_matches_reference() {
    // btc-rsi.xlsx: timestamp(0), close(1), ..., rsi(6)
    let cols = read_xlsx_by_position("resources/data/btc-rsi.xlsx", &[1, 6]);
    let closes = &cols[0];
    let expected = &cols[1];

    let data = build_ohlcv_from_closes(closes);

    let mut rsi = RSI::new(RSIConfig::new(14));
    rsi.calc(&data).unwrap();

    let comparisons = compare_values("RSI", rsi.history(), expected, EPSILON);
    println!("RSI: {} values compared successfully", comparisons);
    assert!(
        comparisons > 100,
        "Should have compared many values, got {}",
        comparisons
    );
}

#[test]
fn rsi_streaming_matches_batch() {
    let cols = read_xlsx_by_position("resources/data/btc-rsi.xlsx", &[1]);
    let closes = &cols[0];

    let data = build_ohlcv_from_closes(closes);

    // Batch calculation
    let mut batch_rsi = RSI::new(RSIConfig::new(14));
    batch_rsi.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_rsi = RSI::new(RSIConfig::new(14));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_rsi.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_rsi.len(), stream_rsi.len());

    for i in 0..batch_rsi.len() {
        let batch_val = batch_rsi.get(i as isize).unwrap();
        let stream_val = stream_rsi.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch RSI ({}) and stream RSI ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch RSI ({}) != stream RSI ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

// ============================================================
// Bollinger Bands Reference Tests
// ============================================================

#[test]
fn bb_matches_reference() {
    // btc-bb.xlsx: timestamp(0), close(1), sma(2), upper(3), lower(4)
    let cols = read_xlsx_by_position("resources/data/btc-bb.xlsx", &[1, 2, 3, 4]);
    let closes = &cols[0];
    let expected_middle = &cols[1];
    let expected_upper = &cols[2];
    let expected_lower = &cols[3];

    let data = build_ohlcv_from_closes(closes);

    let mut bb = BB::new(BBConfig::new(20, 2.0));
    bb.calc(&data).unwrap();

    // Extract component values from BBOutput
    let history = bb.history();
    let rust_upper: Vec<f64> = history.iter().map(|o| o.upper).collect();
    let rust_middle: Vec<f64> = history.iter().map(|o| o.middle).collect();
    let rust_lower: Vec<f64> = history.iter().map(|o| o.lower).collect();

    let upper_cmp = compare_values("BB Upper", &rust_upper, expected_upper, EPSILON);
    let middle_cmp = compare_values("BB Middle", &rust_middle, expected_middle, EPSILON);
    let lower_cmp = compare_values("BB Lower", &rust_lower, expected_lower, EPSILON);

    println!(
        "BB: upper={}, middle={}, lower={} values compared successfully",
        upper_cmp, middle_cmp, lower_cmp
    );
    assert!(
        upper_cmp > 100,
        "Should have compared many upper values, got {}",
        upper_cmp
    );
    assert!(
        middle_cmp > 100,
        "Should have compared many middle values, got {}",
        middle_cmp
    );
    assert!(
        lower_cmp > 100,
        "Should have compared many lower values, got {}",
        lower_cmp
    );
}

#[test]
fn bb_streaming_matches_batch() {
    let cols = read_xlsx_by_position("resources/data/btc-bb.xlsx", &[1]);
    let closes = &cols[0];

    let data = build_ohlcv_from_closes(closes);

    // Batch calculation
    let mut batch_bb = BB::new(BBConfig::new(20, 2.0));
    batch_bb.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_bb = BB::new(BBConfig::new(20, 2.0));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_bb.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_bb.len(), stream_bb.len());

    for i in 0..batch_bb.len() {
        let batch_val = batch_bb.get(i as isize).unwrap();
        let stream_val = stream_bb.get(i as isize).unwrap();

        // Compare upper band
        if batch_val.upper.is_nan() && stream_val.upper.is_nan() {
            // Both NaN is ok
        } else if batch_val.upper.is_nan() || stream_val.upper.is_nan() {
            panic!(
                "Index {}: batch BB upper ({}) and stream BB upper ({}) NaN mismatch",
                i, batch_val.upper, stream_val.upper
            );
        } else {
            assert!(
                (batch_val.upper - stream_val.upper).abs() < epsilon,
                "Index {}: batch BB upper ({}) != stream BB upper ({})",
                i,
                batch_val.upper,
                stream_val.upper
            );
        }

        // Compare middle band
        if batch_val.middle.is_nan() && stream_val.middle.is_nan() {
            // Both NaN is ok
        } else if batch_val.middle.is_nan() || stream_val.middle.is_nan() {
            panic!(
                "Index {}: batch BB middle ({}) and stream BB middle ({}) NaN mismatch",
                i, batch_val.middle, stream_val.middle
            );
        } else {
            assert!(
                (batch_val.middle - stream_val.middle).abs() < epsilon,
                "Index {}: batch BB middle ({}) != stream BB middle ({})",
                i,
                batch_val.middle,
                stream_val.middle
            );
        }

        // Compare lower band
        if batch_val.lower.is_nan() && stream_val.lower.is_nan() {
            // Both NaN is ok
        } else if batch_val.lower.is_nan() || stream_val.lower.is_nan() {
            panic!(
                "Index {}: batch BB lower ({}) and stream BB lower ({}) NaN mismatch",
                i, batch_val.lower, stream_val.lower
            );
        } else {
            assert!(
                (batch_val.lower - stream_val.lower).abs() < epsilon,
                "Index {}: batch BB lower ({}) != stream BB lower ({})",
                i,
                batch_val.lower,
                stream_val.lower
            );
        }
    }
}

// ============================================================
// ATR Reference Tests
// ============================================================

#[test]
fn atr_matches_reference() {
    // btc-atr.xlsx: timestamp(0), high(1), low(2), close(3), tr(4), atr(5)
    let cols = read_xlsx_by_position("resources/data/btc-atr.xlsx", &[1, 2, 3, 4, 5]);
    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];
    let expected_tr = &cols[3];
    let expected_atr = &cols[4];

    let data = build_ohlcv_hlc(highs, lows, closes);

    // Test TR
    let mut tr = TR::default();
    tr.calc(&data).unwrap();
    let tr_comparisons = compare_values("TR", tr.history(), expected_tr, EPSILON);
    println!("TR: {} values compared successfully", tr_comparisons);

    // Test ATR
    let mut atr = ATR::new(ATRConfig::new(14));
    atr.calc(&data).unwrap();
    let atr_comparisons = compare_values("ATR", atr.history(), expected_atr, EPSILON);
    println!("ATR: {} values compared successfully", atr_comparisons);

    assert!(
        tr_comparisons > 100,
        "Should have compared many TR values, got {}",
        tr_comparisons
    );
    assert!(
        atr_comparisons > 100,
        "Should have compared many ATR values, got {}",
        atr_comparisons
    );
}

#[test]
fn atr_streaming_matches_batch() {
    let cols = read_xlsx_by_position("resources/data/btc-atr.xlsx", &[1, 2, 3]);
    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];

    let data = build_ohlcv_hlc(highs, lows, closes);

    // Batch calculation
    let mut batch_atr = ATR::new(ATRConfig::new(14));
    batch_atr.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_atr = ATR::new(ATRConfig::new(14));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_atr.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_atr.len(), stream_atr.len());

    for i in 0..batch_atr.len() {
        let batch_val = batch_atr.get(i as isize).unwrap();
        let stream_val = stream_atr.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch ATR ({}) and stream ATR ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch ATR ({}) != stream ATR ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

// ============================================================
// OBV Reference Tests
// ============================================================

#[test]
fn obv_matches_reference() {
    // btc-obv.xlsx: timestamp(0), close(1), volume(2), up(3), down(4), obv(5)
    let cols = read_xlsx_by_position("resources/data/btc-obv.xlsx", &[1, 2, 5]);
    let closes = &cols[0];
    let volumes = &cols[1];
    let expected = &cols[2];

    let data = build_ohlcv_cv(closes, volumes);

    let mut obv = OBV::default();
    obv.calc(&data).unwrap();

    let history = obv.history();

    // OBV uses relative error due to large values
    let mut comparisons = 0;
    for (i, (rust_val, true_val)) in history.iter().zip(expected.iter()).enumerate() {
        if !rust_val.is_nan() && !true_val.is_nan() {
            let diff = (rust_val - true_val).abs();
            let relative_err = if true_val.abs() > 1.0 {
                diff / true_val.abs()
            } else {
                diff
            };
            assert!(
                relative_err < 0.001, // 0.1% tolerance
                "OBV mismatch at index {}: Rust={:.6}, Expected={:.6}, diff={:.6}",
                i,
                rust_val,
                true_val,
                diff
            );
            comparisons += 1;
        }
    }

    println!("OBV: {} values compared successfully", comparisons);
    assert!(
        comparisons > 100,
        "Should have compared many values, got {}",
        comparisons
    );
}

#[test]
fn obv_streaming_matches_batch() {
    let cols = read_xlsx_by_position("resources/data/btc-obv.xlsx", &[1, 2]);
    let closes = &cols[0];
    let volumes = &cols[1];

    let data = build_ohlcv_cv(closes, volumes);

    // Batch calculation
    let mut batch_obv = OBV::default();
    batch_obv.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_obv = OBV::default();
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_obv.update(&tick).unwrap();
    }

    // Compare results - OBV uses absolute values, so use small epsilon
    let epsilon = 1e-6;
    assert_eq!(batch_obv.len(), stream_obv.len());

    for i in 0..batch_obv.len() {
        let batch_val = batch_obv.get(i as isize).unwrap();
        let stream_val = stream_obv.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch OBV ({}) and stream OBV ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch OBV ({}) != stream OBV ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

// ============================================================
// ADX Reference Tests
// ============================================================

#[test]
fn adx_matches_reference() {
    // btc-adx.xlsx: timestamp(0), high(1), low(2), close(3), ..., +dmi(12), -dmi(13), dx(14), adx(15)
    let cols = read_xlsx_by_position(
        "resources/data/btc-adx.xlsx",
        &[1, 2, 3, 12, 13, 14, 15],
    );
    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];
    let expected_plus_di = &cols[3];
    let expected_minus_di = &cols[4];
    let expected_dx = &cols[5];
    let expected_adx = &cols[6];

    let data = build_ohlcv_hlc(highs, lows, closes);

    let mut adx = ADX::new(ADXConfig::new(14, 14));
    adx.calc(&data).unwrap();

    let history = adx.history();

    // Compare +DI
    let rust_plus_di: Vec<f64> = history.iter().map(|o| o.plus_di).collect();
    let plus_di_cmp = compare_values("+DI", &rust_plus_di, expected_plus_di, EPSILON);
    println!("+DI: {} values compared successfully", plus_di_cmp);

    // Compare -DI
    let rust_minus_di: Vec<f64> = history.iter().map(|o| o.minus_di).collect();
    let minus_di_cmp = compare_values("-DI", &rust_minus_di, expected_minus_di, EPSILON);
    println!("-DI: {} values compared successfully", minus_di_cmp);

    // Compare DX
    let rust_dx: Vec<f64> = history.iter().map(|o| o.dx).collect();
    let dx_cmp = compare_values("DX", &rust_dx, expected_dx, EPSILON);
    println!("DX: {} values compared successfully", dx_cmp);

    // Compare ADX
    let rust_adx: Vec<f64> = history.iter().map(|o| o.adx).collect();
    let adx_cmp = compare_values("ADX", &rust_adx, expected_adx, EPSILON);
    println!("ADX: {} values compared successfully", adx_cmp);

    // All should have significant comparisons
    assert!(
        plus_di_cmp > 100,
        "Should have compared many +DI values, got {}",
        plus_di_cmp
    );
    assert!(
        minus_di_cmp > 100,
        "Should have compared many -DI values, got {}",
        minus_di_cmp
    );
    assert!(
        dx_cmp > 100,
        "Should have compared many DX values, got {}",
        dx_cmp
    );
    assert!(
        adx_cmp > 100,
        "Should have compared many ADX values, got {}",
        adx_cmp
    );
}

#[test]
fn adx_streaming_matches_batch() {
    let cols = read_xlsx_by_position("resources/data/btc-adx.xlsx", &[1, 2, 3]);
    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];

    let data = build_ohlcv_hlc(highs, lows, closes);

    // Batch calculation
    let mut batch_adx = ADX::new(ADXConfig::new(14, 14));
    batch_adx.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_adx = ADX::new(ADXConfig::new(14, 14));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_adx.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_adx.len(), stream_adx.len());

    for i in 0..batch_adx.len() {
        let batch_val = batch_adx.get(i as isize).unwrap();
        let stream_val = stream_adx.get(i as isize).unwrap();

        // Compare +DI
        if batch_val.plus_di.is_nan() && stream_val.plus_di.is_nan() {
            // Both NaN is ok
        } else if batch_val.plus_di.is_nan() || stream_val.plus_di.is_nan() {
            panic!(
                "Index {}: batch +DI ({}) and stream +DI ({}) NaN mismatch",
                i, batch_val.plus_di, stream_val.plus_di
            );
        } else {
            assert!(
                (batch_val.plus_di - stream_val.plus_di).abs() < epsilon,
                "Index {}: batch +DI ({}) != stream +DI ({})",
                i,
                batch_val.plus_di,
                stream_val.plus_di
            );
        }

        // Compare -DI
        if batch_val.minus_di.is_nan() && stream_val.minus_di.is_nan() {
            // Both NaN is ok
        } else if batch_val.minus_di.is_nan() || stream_val.minus_di.is_nan() {
            panic!(
                "Index {}: batch -DI ({}) and stream -DI ({}) NaN mismatch",
                i, batch_val.minus_di, stream_val.minus_di
            );
        } else {
            assert!(
                (batch_val.minus_di - stream_val.minus_di).abs() < epsilon,
                "Index {}: batch -DI ({}) != stream -DI ({})",
                i,
                batch_val.minus_di,
                stream_val.minus_di
            );
        }

        // Compare DX
        if batch_val.dx.is_nan() && stream_val.dx.is_nan() {
            // Both NaN is ok
        } else if batch_val.dx.is_nan() || stream_val.dx.is_nan() {
            panic!(
                "Index {}: batch DX ({}) and stream DX ({}) NaN mismatch",
                i, batch_val.dx, stream_val.dx
            );
        } else {
            assert!(
                (batch_val.dx - stream_val.dx).abs() < epsilon,
                "Index {}: batch DX ({}) != stream DX ({})",
                i,
                batch_val.dx,
                stream_val.dx
            );
        }

        // Compare ADX (has longer warmup period, may be NaN)
        if batch_val.adx.is_nan() && stream_val.adx.is_nan() {
            // Both NaN is ok
        } else if batch_val.adx.is_nan() || stream_val.adx.is_nan() {
            panic!(
                "Index {}: batch ADX ({}) and stream ADX ({}) NaN mismatch",
                i, batch_val.adx, stream_val.adx
            );
        } else {
            assert!(
                (batch_val.adx - stream_val.adx).abs() < epsilon,
                "Index {}: batch ADX ({}) != stream ADX ({})",
                i,
                batch_val.adx,
                stream_val.adx
            );
        }
    }
}

#[test]
fn linear_regression_matches_reference() {
    // Column positions from data_sheets.py:
    // timestamp(0), high(1), low(2), close(3), typical(4), row(5), intercept(6), slope(7), lr2(8), forecast(9)
    let cols = read_xlsx_by_position(
        "resources/data/btc-linear_regression.xlsx",
        &[1, 2, 3, 6, 7], // high, low, close, intercept, slope
    );

    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];
    let expected_intercept = &cols[3];
    let expected_slope = &cols[4];

    let data = build_ohlcv_hlc(highs, lows, closes);
    let mut lr = LinearRegression::new(LinearRegressionConfig::new(14));

    lr.calc(&data).unwrap();

    assert_eq!(lr.len(), data.len());

    // LinearRegression outputs fitted value: slope * (period - 1) + intercept
    // We reconstruct expected from slope/intercept columns
    let period = 14;
    let mut expected_lr: Vec<f64> = vec![f64::NAN; data.len()];
    for i in (period - 1)..data.len() {
        if !expected_slope[i].is_nan() && !expected_intercept[i].is_nan() {
            expected_lr[i] = expected_slope[i] * (period - 1) as f64 + expected_intercept[i];
        }
    }

    let rust_lr: Vec<f64> = lr.history().to_vec();
    let lr_cmp = compare_values("LR", &rust_lr, &expected_lr, EPSILON);

    assert!(
        lr_cmp > 100,
        "Should have compared many LR values, got {}",
        lr_cmp
    );
}

#[test]
fn linear_regression_r2_matches_reference() {
    // Column positions: timestamp(0), high(1), low(2), close(3), typical(4), row(5), intercept(6), slope(7), lr2(8), forecast(9)
    let cols = read_xlsx_by_position(
        "resources/data/btc-linear_regression.xlsx",
        &[1, 2, 3, 8], // high, low, close, lr2
    );

    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];
    let expected_lr2 = &cols[3];

    let data = build_ohlcv_hlc(highs, lows, closes);
    let mut lr2 = LinearRegressionR2::new(LinearRegressionConfig::new(14));

    lr2.calc(&data).unwrap();

    assert_eq!(lr2.len(), data.len());

    let rust_lr2: Vec<f64> = lr2.history().to_vec();
    let lr2_cmp = compare_values("LR2", &rust_lr2, expected_lr2, EPSILON);

    assert!(
        lr2_cmp > 100,
        "Should have compared many LR2 (R²) values, got {}",
        lr2_cmp
    );
}

#[test]
fn linear_regression_forecast_matches_reference() {
    // Column positions: timestamp(0), high(1), low(2), close(3), typical(4), row(5), intercept(6), slope(7), lr2(8), forecast(9)
    let cols = read_xlsx_by_position(
        "resources/data/btc-linear_regression.xlsx",
        &[1, 2, 3, 9], // high, low, close, forecast
    );

    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];
    let expected_lrf = &cols[3];

    let data = build_ohlcv_hlc(highs, lows, closes);
    let mut lrf = LinearRegressionForecast::new(LinearRegressionConfig::new(14));

    lrf.calc(&data).unwrap();

    assert_eq!(lrf.len(), data.len());

    let rust_lrf: Vec<f64> = lrf.history().to_vec();
    let lrf_cmp = compare_values("LRF", &rust_lrf, expected_lrf, EPSILON);

    assert!(
        lrf_cmp > 100,
        "Should have compared many LRF (forecast) values, got {}",
        lrf_cmp
    );
}

#[test]
fn linear_regression_streaming_matches_batch() {
    let cols = read_xlsx_by_position(
        "resources/data/btc-linear_regression.xlsx",
        &[1, 2, 3], // high, low, close
    );

    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];

    let data = build_ohlcv_hlc(highs, lows, closes);

    // Batch calculation
    let mut batch_lr = LinearRegression::new(LinearRegressionConfig::new(14));
    batch_lr.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_lr = LinearRegression::new(LinearRegressionConfig::new(14));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_lr.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_lr.len(), stream_lr.len());

    for i in 0..batch_lr.len() {
        let batch_val = batch_lr.get(i as isize).unwrap();
        let stream_val = stream_lr.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch LR ({}) and stream LR ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch LR ({}) != stream LR ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

#[test]
fn linear_regression_r2_streaming_matches_batch() {
    let cols = read_xlsx_by_position(
        "resources/data/btc-linear_regression.xlsx",
        &[1, 2, 3], // high, low, close
    );

    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];

    let data = build_ohlcv_hlc(highs, lows, closes);

    // Batch calculation
    let mut batch_lr2 = LinearRegressionR2::new(LinearRegressionConfig::new(14));
    batch_lr2.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_lr2 = LinearRegressionR2::new(LinearRegressionConfig::new(14));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_lr2.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_lr2.len(), stream_lr2.len());

    for i in 0..batch_lr2.len() {
        let batch_val = batch_lr2.get(i as isize).unwrap();
        let stream_val = stream_lr2.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch LR2 ({}) and stream LR2 ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch LR2 ({}) != stream LR2 ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

#[test]
fn linear_regression_forecast_streaming_matches_batch() {
    let cols = read_xlsx_by_position(
        "resources/data/btc-linear_regression.xlsx",
        &[1, 2, 3], // high, low, close
    );

    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];

    let data = build_ohlcv_hlc(highs, lows, closes);

    // Batch calculation
    let mut batch_lrf = LinearRegressionForecast::new(LinearRegressionConfig::new(14));
    batch_lrf.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_lrf = LinearRegressionForecast::new(LinearRegressionConfig::new(14));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_lrf.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_lrf.len(), stream_lrf.len());

    for i in 0..batch_lrf.len() {
        let batch_val = batch_lrf.get(i as isize).unwrap();
        let stream_val = stream_lrf.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch LRF ({}) and stream LRF ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch LRF ({}) != stream LRF ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

// ============================================================
// Hybrid Mode Tests (50% bulk + 50% incremental)
// These tests verify indicators can initialize with batch data
// and then continue receiving live updates correctly.
// ============================================================

#[test]
fn sma_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-sma.xlsx", &[1]);
    let closes = &cols[0];
    let data = build_ohlcv_from_closes(closes);

    // Full batch for reference
    let mut batch_sma = SMA::new(SMAConfig::new(14));
    batch_sma.calc(&data).unwrap();

    // Hybrid: 50% bulk, then incremental
    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_sma = SMA::new(SMAConfig::new(14));
    hybrid_sma.calc(&first_half).unwrap();

    // Continue with incremental updates
    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_sma.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_sma.len(), hybrid_sma.len());

    for i in 0..batch_sma.len() {
        let batch_val = batch_sma.get(i as isize).unwrap();
        let hybrid_val = hybrid_sma.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "SMA hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "SMA hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}

#[test]
fn ema_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-ema.xlsx", &[1]);
    let closes = &cols[0];
    let data = build_ohlcv_from_closes(closes);

    let mut batch_ema = EMA::new(EMAConfig::new(14));
    batch_ema.calc(&data).unwrap();

    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_ema = EMA::new(EMAConfig::new(14));
    hybrid_ema.calc(&first_half).unwrap();

    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_ema.update(&tick).unwrap();
    }

    let epsilon = 1e-6;
    assert_eq!(batch_ema.len(), hybrid_ema.len());

    for i in 0..batch_ema.len() {
        let batch_val = batch_ema.get(i as isize).unwrap();
        let hybrid_val = hybrid_ema.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "EMA hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "EMA hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}

#[test]
fn wma_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-wma.xlsx", &[1]);
    let closes = &cols[0];
    let data = build_ohlcv_from_closes(closes);

    let mut batch_wma = WMA::new(WMAConfig::new(14));
    batch_wma.calc(&data).unwrap();

    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_wma = WMA::new(WMAConfig::new(14));
    hybrid_wma.calc(&first_half).unwrap();

    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_wma.update(&tick).unwrap();
    }

    let epsilon = 1e-6;
    assert_eq!(batch_wma.len(), hybrid_wma.len());

    for i in 0..batch_wma.len() {
        let batch_val = batch_wma.get(i as isize).unwrap();
        let hybrid_val = hybrid_wma.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "WMA hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "WMA hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}

#[test]
fn hma_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-hma.xlsx", &[1]);
    let closes = &cols[0];
    let data = build_ohlcv_from_closes(closes);

    let mut batch_hma = HMA::new(HMAConfig::new(14));
    batch_hma.calc(&data).unwrap();

    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_hma = HMA::new(HMAConfig::new(14));
    hybrid_hma.calc(&first_half).unwrap();

    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_hma.update(&tick).unwrap();
    }

    let epsilon = 1e-6;
    assert_eq!(batch_hma.len(), hybrid_hma.len());

    for i in 0..batch_hma.len() {
        let batch_val = batch_hma.get(i as isize).unwrap();
        let hybrid_val = hybrid_hma.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "HMA hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "HMA hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}

#[test]
fn rsi_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-rsi.xlsx", &[1]);
    let closes = &cols[0];
    let data = build_ohlcv_from_closes(closes);

    let mut batch_rsi = RSI::new(RSIConfig::new(14));
    batch_rsi.calc(&data).unwrap();

    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_rsi = RSI::new(RSIConfig::new(14));
    hybrid_rsi.calc(&first_half).unwrap();

    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_rsi.update(&tick).unwrap();
    }

    let epsilon = 1e-6;
    assert_eq!(batch_rsi.len(), hybrid_rsi.len());

    for i in 0..batch_rsi.len() {
        let batch_val = batch_rsi.get(i as isize).unwrap();
        let hybrid_val = hybrid_rsi.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "RSI hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "RSI hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}

#[test]
fn bb_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-bb.xlsx", &[1]);
    let closes = &cols[0];
    let data = build_ohlcv_from_closes(closes);

    let mut batch_bb = BB::new(BBConfig::new(20, 2.0));
    batch_bb.calc(&data).unwrap();

    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_bb = BB::new(BBConfig::new(20, 2.0));
    hybrid_bb.calc(&first_half).unwrap();

    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_bb.update(&tick).unwrap();
    }

    let epsilon = 1e-6;
    assert_eq!(batch_bb.len(), hybrid_bb.len());

    for i in 0..batch_bb.len() {
        let batch_val = batch_bb.get(i as isize).unwrap();
        let hybrid_val = hybrid_bb.get(i as isize).unwrap();

        // Compare upper
        if !batch_val.upper.is_nan() && !hybrid_val.upper.is_nan() {
            assert!(
                (batch_val.upper - hybrid_val.upper).abs() < epsilon,
                "BB upper hybrid mismatch at index {}: batch={}, hybrid={}",
                i,
                batch_val.upper,
                hybrid_val.upper
            );
        }

        // Compare middle
        if !batch_val.middle.is_nan() && !hybrid_val.middle.is_nan() {
            assert!(
                (batch_val.middle - hybrid_val.middle).abs() < epsilon,
                "BB middle hybrid mismatch at index {}: batch={}, hybrid={}",
                i,
                batch_val.middle,
                hybrid_val.middle
            );
        }

        // Compare lower
        if !batch_val.lower.is_nan() && !hybrid_val.lower.is_nan() {
            assert!(
                (batch_val.lower - hybrid_val.lower).abs() < epsilon,
                "BB lower hybrid mismatch at index {}: batch={}, hybrid={}",
                i,
                batch_val.lower,
                hybrid_val.lower
            );
        }
    }
}

#[test]
fn atr_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-atr.xlsx", &[1, 2, 3]);
    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];
    let data = build_ohlcv_hlc(highs, lows, closes);

    let mut batch_atr = ATR::new(ATRConfig::new(14));
    batch_atr.calc(&data).unwrap();

    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_atr = ATR::new(ATRConfig::new(14));
    hybrid_atr.calc(&first_half).unwrap();

    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_atr.update(&tick).unwrap();
    }

    let epsilon = 1e-6;
    assert_eq!(batch_atr.len(), hybrid_atr.len());

    for i in 0..batch_atr.len() {
        let batch_val = batch_atr.get(i as isize).unwrap();
        let hybrid_val = hybrid_atr.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "ATR hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "ATR hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}

#[test]
fn obv_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-obv.xlsx", &[1, 2]);
    let closes = &cols[0];
    let volumes = &cols[1];
    let data = build_ohlcv_cv(closes, volumes);

    let mut batch_obv = OBV::default();
    batch_obv.calc(&data).unwrap();

    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_obv = OBV::default();
    hybrid_obv.calc(&first_half).unwrap();

    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_obv.update(&tick).unwrap();
    }

    let epsilon = 1e-6;
    assert_eq!(batch_obv.len(), hybrid_obv.len());

    for i in 0..batch_obv.len() {
        let batch_val = batch_obv.get(i as isize).unwrap();
        let hybrid_val = hybrid_obv.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "OBV hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "OBV hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}

#[test]
fn adx_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-adx.xlsx", &[1, 2, 3]);
    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];
    let data = build_ohlcv_hlc(highs, lows, closes);

    let mut batch_adx = ADX::new(ADXConfig::new(14, 14));
    batch_adx.calc(&data).unwrap();

    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_adx = ADX::new(ADXConfig::new(14, 14));
    hybrid_adx.calc(&first_half).unwrap();

    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_adx.update(&tick).unwrap();
    }

    let epsilon = 1e-6;
    assert_eq!(batch_adx.len(), hybrid_adx.len());

    for i in 0..batch_adx.len() {
        let batch_val = batch_adx.get(i as isize).unwrap();
        let hybrid_val = hybrid_adx.get(i as isize).unwrap();

        // Compare +DI
        if !batch_val.plus_di.is_nan() && !hybrid_val.plus_di.is_nan() {
            assert!(
                (batch_val.plus_di - hybrid_val.plus_di).abs() < epsilon,
                "ADX +DI hybrid mismatch at index {}: batch={}, hybrid={}",
                i,
                batch_val.plus_di,
                hybrid_val.plus_di
            );
        }

        // Compare -DI
        if !batch_val.minus_di.is_nan() && !hybrid_val.minus_di.is_nan() {
            assert!(
                (batch_val.minus_di - hybrid_val.minus_di).abs() < epsilon,
                "ADX -DI hybrid mismatch at index {}: batch={}, hybrid={}",
                i,
                batch_val.minus_di,
                hybrid_val.minus_di
            );
        }

        // Compare DX
        if !batch_val.dx.is_nan() && !hybrid_val.dx.is_nan() {
            assert!(
                (batch_val.dx - hybrid_val.dx).abs() < epsilon,
                "ADX DX hybrid mismatch at index {}: batch={}, hybrid={}",
                i,
                batch_val.dx,
                hybrid_val.dx
            );
        }

        // Compare ADX
        if !batch_val.adx.is_nan() && !hybrid_val.adx.is_nan() {
            assert!(
                (batch_val.adx - hybrid_val.adx).abs() < epsilon,
                "ADX hybrid mismatch at index {}: batch={}, hybrid={}",
                i,
                batch_val.adx,
                hybrid_val.adx
            );
        }
    }
}

#[test]
fn linear_regression_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-linear_regression.xlsx", &[1, 2, 3]);
    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];
    let data = build_ohlcv_hlc(highs, lows, closes);

    let mut batch_lr = LinearRegression::new(LinearRegressionConfig::new(14));
    batch_lr.calc(&data).unwrap();

    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_lr = LinearRegression::new(LinearRegressionConfig::new(14));
    hybrid_lr.calc(&first_half).unwrap();

    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_lr.update(&tick).unwrap();
    }

    let epsilon = 1e-6;
    assert_eq!(batch_lr.len(), hybrid_lr.len());

    for i in 0..batch_lr.len() {
        let batch_val = batch_lr.get(i as isize).unwrap();
        let hybrid_val = hybrid_lr.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "LR hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "LR hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}

#[test]
fn linear_regression_r2_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-linear_regression.xlsx", &[1, 2, 3]);
    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];
    let data = build_ohlcv_hlc(highs, lows, closes);

    let mut batch_lr2 = LinearRegressionR2::new(LinearRegressionConfig::new(14));
    batch_lr2.calc(&data).unwrap();

    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_lr2 = LinearRegressionR2::new(LinearRegressionConfig::new(14));
    hybrid_lr2.calc(&first_half).unwrap();

    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_lr2.update(&tick).unwrap();
    }

    let epsilon = 1e-6;
    assert_eq!(batch_lr2.len(), hybrid_lr2.len());

    for i in 0..batch_lr2.len() {
        let batch_val = batch_lr2.get(i as isize).unwrap();
        let hybrid_val = hybrid_lr2.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "LR2 hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "LR2 hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}

#[test]
fn linear_regression_forecast_hybrid_mode() {
    let cols = read_xlsx_by_position("resources/data/btc-linear_regression.xlsx", &[1, 2, 3]);
    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];
    let data = build_ohlcv_hlc(highs, lows, closes);

    let mut batch_lrf = LinearRegressionForecast::new(LinearRegressionConfig::new(14));
    batch_lrf.calc(&data).unwrap();

    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_lrf = LinearRegressionForecast::new(LinearRegressionConfig::new(14));
    hybrid_lrf.calc(&first_half).unwrap();

    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_lrf.update(&tick).unwrap();
    }

    let epsilon = 1e-6;
    assert_eq!(batch_lrf.len(), hybrid_lrf.len());

    for i in 0..batch_lrf.len() {
        let batch_val = batch_lrf.get(i as isize).unwrap();
        let hybrid_val = hybrid_lrf.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "LRF hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "LRF hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}

#[test]
fn linear_regression_optimized_path() {
    // Test the calc_from_models() optimization path
    let cols = read_xlsx_by_position(
        "resources/data/btc-linear_regression.xlsx",
        &[1, 2, 3, 8, 9], // high, low, close, lr2, forecast
    );

    let highs = &cols[0];
    let lows = &cols[1];
    let closes = &cols[2];
    let expected_lr2 = &cols[3];
    let expected_lrf = &cols[4];

    let data = build_ohlcv_hlc(highs, lows, closes);

    // Calculate LR once
    let mut lr = LinearRegression::new(LinearRegressionConfig::new(14));
    lr.calc(&data).unwrap();

    // Reuse models for LR2
    let mut lr2_optimized = LinearRegressionR2::new(LinearRegressionConfig::new(14));
    lr2_optimized.calc_from_models(&data, lr.models()).unwrap();

    // Compare against independent calculation
    let mut lr2_independent = LinearRegressionR2::new(LinearRegressionConfig::new(14));
    lr2_independent.calc(&data).unwrap();

    let epsilon = 1e-10;
    for i in 0..lr2_optimized.len() {
        let optimized = lr2_optimized.get(i as isize).unwrap();
        let independent = lr2_independent.get(i as isize).unwrap();

        if optimized.is_nan() && independent.is_nan() {
            continue;
        }

        assert!(
            (optimized - independent).abs() < epsilon,
            "Index {}: optimized LR2 ({}) != independent LR2 ({})",
            i,
            optimized,
            independent
        );
    }

    // Verify against reference
    let rust_lr2: Vec<f64> = lr2_optimized.history().to_vec();
    let lr2_cmp = compare_values("LR2 (optimized)", &rust_lr2, expected_lr2, EPSILON);
    assert!(lr2_cmp > 100);

    // Reuse models for LRF
    let mut lrf_optimized = LinearRegressionForecast::new(LinearRegressionConfig::new(14));
    lrf_optimized.calc_from_models(lr.models()).unwrap();

    // Compare against independent calculation
    let mut lrf_independent = LinearRegressionForecast::new(LinearRegressionConfig::new(14));
    lrf_independent.calc(&data).unwrap();

    for i in 0..lrf_optimized.len() {
        let optimized = lrf_optimized.get(i as isize).unwrap();
        let independent = lrf_independent.get(i as isize).unwrap();

        if optimized.is_nan() && independent.is_nan() {
            continue;
        }

        assert!(
            (optimized - independent).abs() < epsilon,
            "Index {}: optimized LRF ({}) != independent LRF ({})",
            i,
            optimized,
            independent
        );
    }

    // Verify against reference
    let rust_lrf: Vec<f64> = lrf_optimized.history().to_vec();
    let lrf_cmp = compare_values("LRF (optimized)", &rust_lrf, expected_lrf, EPSILON);
    assert!(lrf_cmp > 100);
}

// ============================================================
// VWAP Reference Tests
// ============================================================

#[test]
fn vwap_matches_reference() {
    // btc-vwap.xlsx: timestamp(0), timestamp_mod(1), high(2), low(3), close(4),
    //                typical(5), volume(6), raw_accum(7), vol_accum(8), vwap(9)
    let cols = read_xlsx_by_position(
        "resources/data/btc-vwap.xlsx",
        &[0, 2, 3, 4, 6, 9], // timestamp, high, low, close, volume, vwap
    );
    let timestamps = &cols[0];
    let highs = &cols[1];
    let lows = &cols[2];
    let closes = &cols[3];
    let volumes = &cols[4];
    let expected = &cols[5];

    let data = build_ohlcv_thlcv(timestamps, highs, lows, closes, volumes);

    // Python uses reset_interval = 1440 * 60 = 86400 (daily)
    let mut vwap = VWAP::new(VWAPConfig::new(86400));
    vwap.calc(&data).unwrap();

    let comparisons = compare_values("VWAP", vwap.history(), expected, EPSILON);
    println!("VWAP: {} values compared successfully", comparisons);
    assert!(
        comparisons > 100,
        "Should have compared many values, got {}",
        comparisons
    );
}

#[test]
fn vwap_streaming_matches_batch() {
    let cols = read_xlsx_by_position(
        "resources/data/btc-vwap.xlsx",
        &[0, 2, 3, 4, 6], // timestamp, high, low, close, volume
    );
    let timestamps = &cols[0];
    let highs = &cols[1];
    let lows = &cols[2];
    let closes = &cols[3];
    let volumes = &cols[4];

    let data = build_ohlcv_thlcv(timestamps, highs, lows, closes, volumes);

    // Batch calculation
    let mut batch_vwap = VWAP::new(VWAPConfig::new(86400));
    batch_vwap.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_vwap = VWAP::new(VWAPConfig::new(86400));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_vwap.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_vwap.len(), stream_vwap.len());

    for i in 0..batch_vwap.len() {
        let batch_val = batch_vwap.get(i as isize).unwrap();
        let stream_val = stream_vwap.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch VWAP ({}) and stream VWAP ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch VWAP ({}) != stream VWAP ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

#[test]
fn vwap_hybrid_mode() {
    let cols = read_xlsx_by_position(
        "resources/data/btc-vwap.xlsx",
        &[0, 2, 3, 4, 6], // timestamp, high, low, close, volume
    );
    let timestamps = &cols[0];
    let highs = &cols[1];
    let lows = &cols[2];
    let closes = &cols[3];
    let volumes = &cols[4];

    let data = build_ohlcv_thlcv(timestamps, highs, lows, closes, volumes);

    // Full batch for reference
    let mut batch_vwap = VWAP::new(VWAPConfig::new(86400));
    batch_vwap.calc(&data).unwrap();

    // Hybrid: 50% bulk, then incremental
    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_vwap = VWAP::new(VWAPConfig::new(86400));
    hybrid_vwap.calc(&first_half).unwrap();

    // Continue with incremental updates
    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_vwap.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_vwap.len(), hybrid_vwap.len());

    for i in 0..batch_vwap.len() {
        let batch_val = batch_vwap.get(i as isize).unwrap();
        let hybrid_val = hybrid_vwap.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "VWAP hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "VWAP hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}

// ============================================================
// ROC Reference Tests
// ============================================================

#[test]
fn roc_matches_reference() {
    // btc-roc.xlsx: timestamp(0), open(1), high(2), low(3), close(4), volume(5), roc(6)
    // Excel formula: G15=((E15-E1)/E1)*100 → 14-period lookback where E15=13311 and E1=13319
    let cols = read_xlsx_by_position("resources/data/btc-roc.xlsx", &[4, 6]);
    let closes = &cols[0];
    let expected = &cols[1];

    let data = build_ohlcv_from_closes(closes);

    let mut roc = ROC::new(ROCConfig::new(14)); // Period 14 (Excel row 14 compares to row 1)
    roc.calc(&data).unwrap();

    let history = roc.history();

    let mut comparisons = 0;
    for (i, (rust_val, true_val)) in history.iter().zip(expected.iter()).enumerate() {
        if rust_val.is_nan() && true_val.is_nan() {
            continue;
        }
        if !rust_val.is_nan() && !true_val.is_nan() {
            let diff = (rust_val - true_val).abs();
            assert!(
                diff < EPSILON,
                "ROC mismatch at index {}: Rust={:.6}, Expected={:.6}, diff={:.6}",
                i,
                rust_val,
                true_val,
                diff
            );
            comparisons += 1;
        }
    }

    println!("ROC: {} values compared successfully", comparisons);
    assert!(
        comparisons > 100,
        "Should have compared many ROC values, got {}",
        comparisons
    );
}

#[test]
fn roc_streaming_matches_batch() {
    // btc-roc.xlsx: timestamp(0), open(1), high(2), low(3), close(4), volume(5), roc_14(6)
    let cols = read_xlsx_by_position("resources/data/btc-roc.xlsx", &[4]);
    let closes = &cols[0];

    let data = build_ohlcv_from_closes(closes);

    // Batch calculation
    let mut batch_roc = ROC::new(ROCConfig::new(14));
    batch_roc.calc(&data).unwrap();

    // Streaming calculation
    let mut stream_roc = ROC::new(ROCConfig::new(14));
    for i in 0..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        stream_roc.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_roc.len(), stream_roc.len());

    for i in 0..batch_roc.len() {
        let batch_val = batch_roc.get(i as isize).unwrap();
        let stream_val = stream_roc.get(i as isize).unwrap();

        // Handle NaN
        if batch_val.is_nan() && stream_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || stream_val.is_nan() {
            panic!(
                "Index {}: batch ROC ({}) and stream ROC ({}) NaN mismatch",
                i, batch_val, stream_val
            );
        }

        assert!(
            (batch_val - stream_val).abs() < epsilon,
            "Index {}: batch ROC ({}) != stream ROC ({})",
            i,
            batch_val,
            stream_val
        );
    }
}

#[test]
fn roc_hybrid_mode() {
    // btc-roc.xlsx: timestamp(0), open(1), high(2), low(3), close(4), volume(5), roc_14(6)
    let cols = read_xlsx_by_position("resources/data/btc-roc.xlsx", &[4]);
    let closes = &cols[0];
    let data = build_ohlcv_from_closes(closes);

    // Full batch for reference
    let mut batch_roc = ROC::new(ROCConfig::new(14));
    batch_roc.calc(&data).unwrap();

    // Hybrid: 50% bulk, then incremental
    let half = data.len() / 2;
    let first_half = OhlcvSeries {
        timestamps: data.timestamps[..half].to_vec(),
        opens: data.opens[..half].to_vec(),
        highs: data.highs[..half].to_vec(),
        lows: data.lows[..half].to_vec(),
        closes: data.closes[..half].to_vec(),
        volumes: data.volumes[..half].to_vec(),
    };

    let mut hybrid_roc = ROC::new(ROCConfig::new(14));
    hybrid_roc.calc(&first_half).unwrap();

    // Continue with incremental updates
    for i in half..data.len() {
        let tick = Ohlcv {
            open: data.opens[i].into(),
            high: data.highs[i].into(),
            low: data.lows[i].into(),
            close: data.closes[i].into(),
            volume: data.volumes[i].into(),
            timestamp: data.timestamps[i].into(),
        };
        hybrid_roc.update(&tick).unwrap();
    }

    // Compare results
    let epsilon = 1e-6;
    assert_eq!(batch_roc.len(), hybrid_roc.len());

    for i in 0..batch_roc.len() {
        let batch_val = batch_roc.get(i as isize).unwrap();
        let hybrid_val = hybrid_roc.get(i as isize).unwrap();

        if batch_val.is_nan() && hybrid_val.is_nan() {
            continue;
        } else if batch_val.is_nan() || hybrid_val.is_nan() {
            panic!(
                "ROC hybrid mismatch at index {}: batch={}, hybrid={}",
                i, batch_val, hybrid_val
            );
        }

        assert!(
            (batch_val - hybrid_val).abs() < epsilon,
            "ROC hybrid mismatch at index {}: batch={}, hybrid={}",
            i,
            batch_val,
            hybrid_val
        );
    }
}
